### ISSUE TITLE
Better config for ClusterRoleBindings

### ISSUE THREAD

**Issue by jwietelmann** [revelrylabs/moondog-engine#3]
The way we have things now:

## Can only ever support GitHub as the auth provider

Among other reasons, because of this:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-cluster-auth-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterwide-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ .Values.github.organization }}:{{ .Values.dex.admin_team}}
```

## Requires the installing user to supply redundant values to different parts of the config file

```yaml
github:
  organization: "my-org"
  teams:
    - "Cluster Administrators Team"
    - "Cluster Readonly Team"
```

```yaml
dex:
  readonly_team: "Cluster Administrators Team"
  admin_team: "Cluster Readonly Team"
```

Additionally, those dex config keys don't follow the camelCase convention.

**Comment by jwietelmann** [comment]
This is my idea for a config format that will solve some of the above problems, as well as get us closer to supporting non-GitHub auth:

```yaml
auth:
  - type: github
    id: github
    oauth:
      clientId:
      clientSecret:
    organizations:
      - name: my-organization
        teams:
          - name: Kubernetes Administrators
            roles:
              - md-admin-all
          - name: Engineers
            roles:
              - md-read-all-except-secrets
  - type: google
    id: google
    oauth:
      clientId:
      clientSecret:
    groups:
      - name: Kubernetes Administrators
        roles:
          - md-admin-all
      - name: Engineers
        roles:
          - md-read-all-except-secrets

roles:
  - name: md-admin-all
    rules:
      - apiGroups:
        - '*'
        resources:
        - '*'
        verbs:
        - '*'
      - nonResourceURLs:
        - '*'
        verbs:
        - '*'
  - name: md-read-all-except-secrets
    rules:
      # ...and so on
```
